//#[allow(unused, non_snake_case, non_camel_case_types, non_upper_case_globals)]
/* automatically generated by rust-bindgen 0.71.1 */
//#[repr(C)]
//#[derive(Copy, Clone)]
//pub struct BxInstructionGenerated {
//    pub meta_info: BxInstructionMetaInfo,
//    pub meta_data: [u8; 8],
//    pub instruction_data: InstructionData,
//}
//#[repr(C)]
//#[derive(Debug, Copy, Clone)]
//pub struct BxInstructionMetaInfo {
//    pub ia_opcode: u16,
//    pub ilen: u8,
//    pub meta_info1: u8,
//}
//#[repr(C)]
//#[derive(Copy, Clone)]
//pub union InstructionData {
//    pub modRMForm: ModRmForm,
//}
//#[repr(C)]
//#[derive(Copy, Clone)]
//pub struct ModRmForm {
//    pub operand_data: operandData,
//    pub displacement: displacementData,
//}
//#[repr(C)]
//#[derive(Copy, Clone)]
//pub union operandData {
//    pub Id: u32,
//    pub Iw: [u16; 2usize],
//    pub Ib: [u8; 4usize],
//}
//#[repr(C)]
//#[derive(Copy, Clone)]
//pub union displacementData {
//    pub displ16u: u16,
//    pub displ32u: u32,
//    pub Id2: u32,
//    pub Iw2: [u16; 2usize],
//    pub Ib2: [u8; 4usize],
//}

use core::fmt::Debug;

use super::{ia_opcodes::Opcode, BxSegregs};

const BX_INSTR_METADATA_DST: usize = 0;
const BX_INSTR_METADATA_SRC1: usize = 1;
const BX_INSTR_METADATA_SRC2: usize = 2;
const BX_INSTR_METADATA_SRC3: usize = 3;
const BX_INSTR_METADATA_CET_SEGOVERRIDE: usize = 3; // share src;
const BX_INSTR_METADATA_SEG: usize = 4;
const BX_INSTR_METADATA_BASE: usize = 5;
const BX_INSTR_METADATA_INDEX: usize = 6;
const BX_INSTR_METADATA_SCALE: usize = 7;

#[repr(C)]
#[derive(Debug, Copy, Clone, Default)]
pub struct BxInstructionGenerated {
    pub opcode: Opcode,
    pub meta_info: BxInstructionMetaInfo,
    pub meta_data: [u8; 8],
    pub modrm_form: ModRmForm,
}

#[repr(C)]
#[derive(Debug, Copy, Clone, Default)]
pub struct BxInstructionMetaInfo {
    //pub ia_opcode: u16,
    pub ia_opcode: Opcode,
    pub ilen: u8,
    pub metainfo1: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone, Default)]
pub struct ModRmForm {
    pub operand_data: operandData,

    pub displ16u: u16,
    pub displ32u: u32,
    pub Id2: u32,
    pub Iw2: [u16; 2usize],
    pub Ib2: [u8; 4usize],
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union operandData {
    pub Id: u32,
    pub Iw: [u16; 2usize],
    pub Ib: [u8; 4usize],
}

impl Debug for operandData {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        unsafe {
            write!(
                f,
                "operandData: Id: {:?} Iw: {:?} Ib {:?}",
                self.Id, self.Iw, self.Ib
            )
        }
    }
}

impl Default for operandData {
    fn default() -> Self {
        Self { Id: 0 }
    }
}

#[repr(C)]
#[derive(Copy, Clone)]
pub union displacementData {
    pub displ16u: u16,
    pub displ32u: u32,
    pub Id2: u32,
    pub Iw2: [u16; 2usize],
    pub Ib2: [u8; 4usize],
}

impl BxInstructionGenerated {
    #[inline]
    pub(super) fn as_32_l(&self) -> u32 {
        u32::from(self.meta_info.metainfo1 & 0x1)
    }

    #[inline]
    pub(super) fn set_sib_scale(&mut self, scale: u32) {
        self.meta_data[BX_INSTR_METADATA_SCALE] = scale as _;
    }

    #[inline]
    pub(super) fn set_sib_base(&mut self, base: u32) {
        self.meta_data[BX_INSTR_METADATA_BASE] = base as _;
    }

    #[inline]
    pub(super) fn set_sib_index(&mut self, index: u32) {
        self.meta_data[BX_INSTR_METADATA_INDEX] = index as _;
    }

    #[inline]
    pub(super) fn seg(&self) -> u8 {
        self.meta_data[BX_INSTR_METADATA_SEG]
    }

    #[inline]
    pub(super) fn set_seg(&mut self, val: BxSegregs) {
        self.meta_data[BX_INSTR_METADATA_SEG] = val as _;
    }

    pub(super) fn set_cet_seg_override(&mut self, val: BxSegregs) {
        self.meta_data[BX_INSTR_METADATA_CET_SEGOVERRIDE] = val as _;
    }

    pub(crate) fn ilen(&self) -> u8 {
        self.meta_info.ilen
    }
    //BX_CPP_INLINE void setSeg(unsigned val) {
    //  metaData[BX_INSTR_METADATA_SEG] = val;
    //}
}
