// Always available (no alloc needed)
pub mod instrumentation;
pub mod decoder;

pub use instrumentation::{
    BranchEvent, BranchType, CacheCntrl, CodeSize, CpuSetupMode, CpuSnapshot, EmuStopReason,
    ExitSet, HookMask, HwInterruptEvent, Instrumentation,
    InvEptType, InvPcidType, IoHookEvent, MemAccessRW, MemHookEvent,
    HookCtx, InstrAction, MemPerms, MemType, MwaitFlags, PrefetchHint, ResetType,
    LinAccess, MemPermViolation, MemUnmapped, MwaitEvent, OpcodeEvent, PhyAccess,
    PrefetchEvent, TlbCntrl, X86Reg,
};
#[cfg(feature = "instrumentation")]
pub use instrumentation::{HookHandle, InstrumentationError, IoHookType, MemHookType};

// Everything below requires alloc (Vec/Box in CPU state, icache, init, etc.)

#[cfg(feature = "alloc")]
pub mod error;
#[cfg(feature = "alloc")]
pub use error::{CpuError, Result};

#[cfg(feature = "alloc")]
pub(crate) mod api_bridge;

#[cfg(feature = "alloc")]
pub(super) mod access;
#[cfg(feature = "alloc")]
pub(super) mod aes;
#[cfg(feature = "alloc")]
pub(super) mod apic;
#[cfg(feature = "alloc")]
pub(super) mod arith16;
#[cfg(feature = "alloc")]
pub(super) mod arith32;
#[cfg(feature = "alloc")]
pub(super) mod arith64;
#[cfg(feature = "alloc")]
pub(super) mod arith8;
#[cfg(feature = "alloc")]
pub(super) mod avx;
#[cfg(feature = "alloc")]
pub(super) mod avx512;
#[cfg(feature = "alloc")]
pub(super) mod avx512_bcast;
#[cfg(feature = "alloc")]
pub(super) mod avx512_bw;
#[cfg(feature = "alloc")]
pub(super) mod avx512_cmp;
#[cfg(feature = "alloc")]
pub(super) mod avx512_cvt;
#[cfg(feature = "alloc")]
pub(super) mod avx512_fma;
#[cfg(feature = "alloc")]
pub(super) mod avx512_gather;
#[cfg(feature = "alloc")]
pub(super) mod avx512_insert;
#[cfg(feature = "alloc")]
pub(super) mod avx512_int;
#[cfg(feature = "alloc")]
pub(super) mod avx512_mask;
#[cfg(feature = "alloc")]
pub(super) mod avx512_misc;
#[cfg(feature = "alloc")]
pub(super) mod avx512_perm;
#[cfg(feature = "alloc")]
pub(super) mod avx512_round;
#[cfg(feature = "alloc")]
pub(super) mod avx512_scalar;
#[cfg(feature = "alloc")]
pub(super) mod bcd;
#[cfg(feature = "alloc")]
pub(super) mod bit;
#[cfg(feature = "alloc")]
pub(super) mod bit16;
#[cfg(feature = "alloc")]
pub(super) mod bit32;
#[cfg(feature = "alloc")]
pub(super) mod bit64;
#[cfg(feature = "alloc")]
pub(super) mod bmi32;
#[cfg(feature = "alloc")]
pub(super) mod bmi64;
#[cfg(feature = "alloc")]
pub mod builder;
#[cfg(feature = "alloc")]
#[allow(clippy::module_inception)]
pub mod cpu;
#[cfg(feature = "alloc")]
mod cpu_getters_and_setters;
#[cfg(feature = "alloc")]
pub(super) mod cpu_macros;
#[cfg(feature = "alloc")]
pub(super) mod crc32;
#[cfg(feature = "alloc")]
pub(super) mod cet;
#[cfg(feature = "alloc")]
pub(super) mod cpudb;
#[cfg(feature = "alloc")]
pub(super) mod cpuid;
#[cfg(feature = "alloc")]
pub(super) mod cpustats;
#[cfg(feature = "alloc")]
pub(super) mod crregs;
#[cfg(feature = "alloc")]
pub(super) mod ctrl_xfer16;
#[cfg(feature = "alloc")]
pub(super) mod ctrl_xfer32;
#[cfg(feature = "alloc")]
pub(super) mod ctrl_xfer64;
#[cfg(feature = "alloc")]
pub(super) mod data_xfer16;
#[cfg(feature = "alloc")]
pub(super) mod data_xfer32;
#[cfg(feature = "alloc")]
pub(super) mod data_xfer64;
#[cfg(feature = "alloc")]
pub(super) mod data_xfer8;
#[cfg(feature = "alloc")]
pub(super) mod data_xfer_ext;
#[cfg(feature = "alloc")]
pub(super) mod descriptor;
#[cfg(feature = "alloc")]
pub(super) mod dispatcher;
#[cfg(feature = "alloc")]
pub mod eflags;
#[cfg(feature = "alloc")]
pub(super) mod event;
#[cfg(feature = "alloc")]
pub(super) mod exception;
#[cfg(feature = "alloc")]
pub(super) mod flag_ctrl;
#[cfg(feature = "alloc")]
pub(super) mod flag_ctrl_pro;
#[cfg(feature = "alloc")]
pub(super) mod fpu;
#[cfg(feature = "alloc")]
pub(super) mod gf2;
#[cfg(feature = "alloc")]
pub(super) mod i387;
#[cfg(feature = "alloc")]
pub(super) mod icache;
#[cfg(feature = "alloc")]
pub(super) mod init;
#[cfg(feature = "alloc")]
pub(super) mod io;
#[cfg(feature = "alloc")]
pub(super) mod lazy_flags;
#[cfg(feature = "alloc")]
pub(super) mod logical16;
#[cfg(feature = "alloc")]
pub(super) mod logical32;
#[cfg(feature = "alloc")]
pub(super) mod logical64;
#[cfg(feature = "alloc")]
pub(super) mod logical8;
#[cfg(feature = "alloc")]
pub(super) mod mmx;
#[cfg(feature = "alloc")]
pub(super) mod msr;
#[cfg(feature = "alloc")]
pub(super) mod mult16;
#[cfg(feature = "alloc")]
pub(super) mod mult32;
#[cfg(feature = "alloc")]
pub(super) mod mult64;
#[cfg(feature = "alloc")]
pub(super) mod mult8;
#[cfg(feature = "alloc")]
pub(super) mod mwait;
#[cfg(feature = "alloc")]
pub(super) mod opcodes_table;
#[cfg(feature = "alloc")]
pub(super) mod paging;
#[cfg(feature = "alloc")]
pub(super) mod proc_ctrl;
#[cfg(feature = "alloc")]
pub(super) mod protect_ctrl;
#[cfg(feature = "alloc")]
pub(super) mod protected_interrupts;
#[cfg(feature = "alloc")]
pub(super) mod rdrand;
#[cfg(feature = "alloc")]
pub(super) mod rusty_box;
#[cfg(feature = "alloc")]
pub(super) mod segment_ctrl_pro;
#[cfg(feature = "alloc")]
pub(super) mod sha;
#[cfg(feature = "alloc")]
pub mod snapshot;
#[cfg(feature = "alloc")]
pub(super) mod shift16;
#[cfg(feature = "alloc")]
pub(super) mod shift32;
#[cfg(feature = "alloc")]
pub(super) mod shift64;
#[cfg(feature = "alloc")]
pub(super) mod shift8;
#[cfg(feature = "alloc")]
pub(super) mod smm;
#[cfg(feature = "alloc")]
pub(super) mod soft_int;
#[cfg(feature = "alloc")]
pub(super) mod softfloat3e;
#[cfg(feature = "alloc")]
pub(super) mod sse;
#[cfg(feature = "alloc")]
pub(super) mod sse_move;
#[cfg(feature = "alloc")]
pub(super) mod sse_pfp;
#[cfg(feature = "alloc")]
pub(super) mod sse_rcp;
#[cfg(feature = "alloc")]
pub(super) mod sse_string;
#[cfg(feature = "alloc")]
pub(super) mod stack;
#[cfg(feature = "alloc")]
pub(super) mod stack16;
#[cfg(feature = "alloc")]
pub(super) mod stack32;
#[cfg(feature = "alloc")]
pub(super) mod stack64;
#[cfg(feature = "alloc")]
pub(super) mod string;
#[cfg(feature = "alloc")]
pub(super) mod svm;
#[cfg(feature = "alloc")]
pub(super) mod tasking;
#[cfg(feature = "alloc")]
pub(super) mod tlb;
#[cfg(feature = "alloc")]
pub(super) mod vm8086;
#[cfg(feature = "alloc")]
pub(super) mod vmcs;
#[cfg(feature = "alloc")]
pub(super) mod vmx;
#[cfg(feature = "alloc")]
pub(super) mod vmx_ctrls;
#[cfg(feature = "alloc")]
pub(super) mod xmm;

#[cfg(feature = "alloc")]
pub use cpu::BxCpuC;
#[cfg(feature = "alloc")]
pub use cpuid::BxCpuIdTrait;

#[cfg(feature = "alloc")]
pub use cpudb::intel::*;
#[cfg(feature = "alloc")]
pub use init::ResetReason;
