//! Opcodes table for instruction handler assignment
//!
//! This module defines the opcodes table structure matching the original C++ `BxOpcodesTable`
//! from `fetchdecode32.cc`. It stores handler function pointers and opflags for each opcode.

use super::{cpu::BxCpuC, cpuid::BxCpuIdTrait, decoder::Instruction, Result};
use bitflags::bitflags;

/// Helper macro to create a type-safe wrapper for a handler function
///
/// This macro creates a wrapper function that can be stored in the opcodes table.
/// The wrapper is type-safe and will work with any `BxCpuC<I>` instance.
///
/// # Example
/// ```ignore
/// make_handler_wrapper!(mov_gd_ed_r_wrapper, data_xfer32::MOV_GdEd_R);
/// ```
///
/// This creates a function `mov_gd_ed_r_wrapper` that can be stored in the table.
#[macro_export]
macro_rules! make_handler_wrapper {
    ($wrapper_name:ident, $handler_fn:path) => {
        /// Wrapper function for handler (generated by make_handler_wrapper! macro)
        pub(super) fn $wrapper_name<I: $crate::cpu::cpuid::BxCpuIdTrait>(
            cpu: &mut $crate::cpu::BxCpuC<'_, I>,
            instr: &$crate::cpu::decoder::Instruction,
        ) -> $crate::cpu::Result<()> {
            $handler_fn(cpu, instr);
            Ok(())
        }
    };
    ($wrapper_name:ident, $handler_fn:path, returns_result) => {
        /// Wrapper function for handler (generated by make_handler_wrapper! macro)
        pub(super) fn $wrapper_name<I: $crate::cpu::cpuid::BxCpuIdTrait>(
            cpu: &mut $crate::cpu::BxCpuC<'_, I>,
            instr: &$crate::cpu::decoder::Instruction,
        ) -> $crate::cpu::Result<()> {
            $handler_fn(cpu, instr)
        }
    };
}

bitflags! {
    /// OpFlags bitflags matching original C++ definitions from `fetchdecode.h`.
    /// These flags indicate feature requirements and special handling for instructions.
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub(super) struct OpFlags: u16 {
        /// End of trace marker
        const TRACE_END = 0x01;

        /// Instruction supports LOCK prefix
        const LOCKABLE = 0x02;

        /// FPU (x87) instruction
        const PREPARE_FPU = 0x04;

        /// MMX instruction
        const PREPARE_MMX = 0x08;

        /// SSE instruction (requires CPU_LEVEL >= 6)
        const PREPARE_SSE = 0x10;

        /// AVX instruction (requires BX_SUPPORT_AVX)
        const PREPARE_AVX = 0x20;

        /// Opmask register instruction (requires BX_SUPPORT_EVEX)
        const PREPARE_OPMASK = 0x40;

        /// EVEX instruction (requires BX_SUPPORT_EVEX)
        const PREPARE_EVEX = 0x80;

        /// EVEX instruction that doesn't support SAE in register form
        const PREPARE_EVEX_NO_SAE = 0x100 | Self::PREPARE_EVEX.bits();

        /// EVEX instruction that doesn't support broadcast
        const PREPARE_EVEX_NO_BROADCAST = 0x200 | Self::PREPARE_EVEX.bits();

        /// EVEX instruction that ignores vector length
        const EVEX_VL_IGNORE = 0x400 | Self::PREPARE_EVEX.bits();

        /// AMX instruction (requires BX_SUPPORT_AMX)
        const PREPARE_AMX = 0x800;
    }
}

bitflags! {
    /// FetchModeMask bitflags matching original C++ definitions from `cpu.h`.
    /// These flags indicate which features are currently available/active in the CPU.
    /// They are checked against OpFlags to determine if an instruction can be executed
    /// or if an error handler should be assigned instead.
    /// Matching C++ definitions in cpu.h:5455-5462
    #[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
    pub(crate) struct FetchModeMask: u32 {
        /// CS.D_B — 32-bit default operand/address size
        const D_B = 1 << 0;

        /// Long64 mode active (CS.L=1 in long mode)
        const LONG64 = 1 << 1;

        /// FPU/MMX available
        const FPU_MMX_OK = 1 << 2;

        /// SSE available (CPU_LEVEL >= 6)
        const SSE_OK = 1 << 3;

        /// AVX available (BX_SUPPORT_AVX)
        const AVX_OK = 1 << 4;

        /// Opmask available (BX_SUPPORT_EVEX)
        const OPMASK_OK = 1 << 5;

        /// EVEX available (BX_SUPPORT_EVEX)
        const EVEX_OK = 1 << 6;

        /// AMX available (BX_SUPPORT_AMX)
        const AMX_OK = 1 << 7;
    }
}

/// Structure for opcode table entries
///
/// This matches the original C++ `bxIAOpcodeTable` structure from `fetchdecode.h:82-93`.
/// Each entry contains handler function pointers and opflags for an instruction.
///
/// The table is indexed by opcode and used by `assign_handler` to select the
/// appropriate execution handler based on whether the instruction is in memory
/// form (modC0 == false) or register form (modC0 == true).
///
/// # Fields
/// - `execute1`: Handler for memory form (when modC0 == false)
///   Matching C++ `BxOpcodesTable[ia_opcode].execute1` in fetchdecode32.cc:2046
/// - `execute2`: Handler for register form (when modC0 == true), or None if not applicable
///   Matching C++ `BxOpcodesTable[ia_opcode].execute2` in fetchdecode32.cc:2059
/// - `opflags`: Feature requirements and special handling flags
///   Matching C++ `BxOpcodesTable[ia_opcode].opflags` in fetchdecode32.cc:2065
pub(super) struct BxOpcodeEntry<I: BxCpuIdTrait> {
    /// Handler function for memory form or primary handler
    /// This is a function pointer that will be called with `&mut BxCpuC<I>` and `&Instruction`
    pub(super) execute1: fn(&mut BxCpuC<'_, I>, &Instruction) -> Result<()>,

    /// Handler function for register form or secondary handler
    /// None if instruction doesn't have a register form
    pub(super) execute2: Option<fn(&mut BxCpuC<'_, I>, &Instruction) -> Result<()>>,

    /// Feature requirements and special handling flags
    pub(super) opflags: OpFlags,
}

/// Get opcode entry for a specific opcode
///
/// This function looks up the opcode in the opcodes table and returns its entry
/// containing handler function pointers and opflags. The table maps opcodes to
/// their execution handlers (execute1 for memory form, execute2 for register form).
///
/// Matching C++ `BxOpcodesTable[ia_opcode]` access in fetchdecode32.cc:2046,2059
///
/// # Parameters
/// - `opcode`: The instruction opcode to look up
///
/// # Returns
/// - `Some(entry)` if the opcode has an entry in the table
/// - `None` if the opcode is not yet implemented in the table
///
/// # Note
/// Since the table is not yet fully populated, this uses a match statement
/// that can be extended incrementally. Once all opcodes are mapped,
/// this can be optimized to use a static array lookup.
pub(super) fn get_opcode_entry<I: BxCpuIdTrait>(
    opcode: crate::cpu::decoder::Opcode,
) -> Option<BxOpcodeEntry<I>> {
    use crate::cpu::decoder::Opcode;

    // Wrapper functions to convert handlers to the correct signature
    fn mov_gd_ed_r_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        crate::cpu::data_xfer32::MOV_GdEd_R(cpu, instr);
        Ok(())
    }

    fn mov_gd_ed_m_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        crate::cpu::data_xfer32::MOV_GdEd_M(cpu, instr)?;
        Ok(())
    }

    fn mov_ed_gd_r_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        crate::cpu::data_xfer32::MOV_EdGd_R(cpu, instr);
        Ok(())
    }

    fn mov_ed_gd_m_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        crate::cpu::data_xfer32::MOV_EdGd_M(cpu, instr)?;
        Ok(())
    }

    fn mov_ed_id_r_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        crate::cpu::data_xfer32::MOV_EdId_R(cpu, instr);
        Ok(())
    }

    fn mov_ed_id_m_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        crate::cpu::data_xfer32::MOV_EdId_M(cpu, instr)?;
        Ok(())
    }

    fn add_eb_gb_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        crate::cpu::arith8::ADD_EbGb(cpu, instr)
    }

    fn add_gb_eb_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        crate::cpu::arith8::ADD_GbEb(cpu, instr)
    }

    fn add_gd_ed_r_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        crate::cpu::arith32::ADD_GdEd_R(cpu, instr);
        Ok(())
    }

    fn add_gd_ed_m_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        crate::cpu::arith32::ADD_GdEd_M(cpu, instr)?;
        Ok(())
    }

    fn add_ed_gd_r_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        crate::cpu::arith32::ADD_EdGd_R(cpu, instr);
        Ok(())
    }

    fn add_ed_gd_m_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        crate::cpu::arith32::ADD_EdGd_M(cpu, instr)?;
        Ok(())
    }

    fn add_eax_id_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        crate::cpu::arith32::ADD_EAX_Id(cpu, instr);
        Ok(())
    }

    fn add_eb_ib_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        crate::cpu::arith8::ADD_EbIb(cpu, instr)
    }

    fn add_ew_ib_r_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        crate::cpu::arith16::ADD_EwIbR(cpu, instr)
    }

    fn add_ew_ib_m_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        crate::cpu::arith16::ADD_EwIbM(cpu, instr)?;
        Ok(())
    }

    fn sub_gd_ed_r_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        crate::cpu::arith32::SUB_GdEd_R(cpu, instr);
        Ok(())
    }

    fn sub_gd_ed_m_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        crate::cpu::arith32::SUB_GdEd_M(cpu, instr)?;
        Ok(())
    }

    fn sub_ed_gd_r_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        crate::cpu::arith32::SUB_EdGd_R(cpu, instr);
        Ok(())
    }

    fn sub_ed_gd_m_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        crate::cpu::arith32::SUB_EdGd_M(cpu, instr)?;
        Ok(())
    }

    fn sub_eax_id_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        crate::cpu::arith32::SUB_EAX_Id(cpu, instr);
        Ok(())
    }

    // Wrapper functions for CMP instructions
    fn cmp_gb_eb_r_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        cpu.cmp_gb_eb_r(instr);
        Ok(())
    }

    fn cmp_gb_eb_m_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        cpu.cmp_gb_eb_m(instr)?;
        Ok(())
    }

    fn cmp_eb_gb_r_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        cpu.cmp_eb_gb_r(instr);
        Ok(())
    }

    fn cmp_eb_gb_m_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        cpu.cmp_eb_gb_m(instr)?;
        Ok(())
    }

    fn cmp_gw_ew_r_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        cpu.cmp_gw_ew_r(instr);
        Ok(())
    }

    fn cmp_gw_ew_m_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        cpu.cmp_gw_ew_m(instr)?;
        Ok(())
    }

    fn cmp_gd_ed_r_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        cpu.cmp_gd_ed_r(instr);
        Ok(())
    }

    fn cmp_gd_ed_m_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        cpu.cmp_gd_ed_m(instr)?;
        Ok(())
    }

    fn cmp_al_ib_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        cpu.cmp_al_ib(instr);
        Ok(())
    }

    fn cmp_ax_iw_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        cpu.cmp_ax_iw(instr);
        Ok(())
    }

    fn cmp_eax_id_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        cpu.cmp_eax_id(instr);
        Ok(())
    }

    fn cmp_ew_iw_r_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        cpu.cmp_ew_iw_r(instr);
        Ok(())
    }

    fn cmp_ew_iw_m_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        cpu.cmp_ew_iw_m(instr)?;
        Ok(())
    }

    fn cmp_ed_id_r_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        cpu.cmp_ed_id_r(instr);
        Ok(())
    }

    fn cmp_ed_id_m_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        cpu.cmp_ed_id_m(instr)?;
        Ok(())
    }

    fn cmp_eb_ib_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        // CMP r/m8, imm8 - implemented inline in execute_instruction
        let dst = instr.dst() as usize;
        let op1 = cpu.read_8bit_regx(dst, instr.extend8bit_l());
        let op2 = instr.ib();
        let result = op1.wrapping_sub(op2);
        cpu.update_flags_sub8(op1, op2, result);
        Ok(())
    }

    // Error handler wrappers (these are used inside get_opcode_entry, so they stay here)
    pub(super) fn bx_error_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        cpu.bx_error(instr)
    }

    fn bx_end_trace_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        _instr: &Instruction,
    ) -> Result<()> {
        // Matching C++ genDummyICacheEntry: sets execute1 = &BX_CPU_C::BxEndTrace
        // BxEndTrace sets async_event |= BX_ASYNC_EVENT_STOP_TRACE
        use super::cpu::BX_ASYNC_EVENT_STOP_TRACE;
        cpu.async_event |= BX_ASYNC_EVENT_STOP_TRACE;
        Ok(())
    }

    fn adc_eb_gb_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        crate::cpu::arith8::ADC_EbGb(cpu, instr)
    }

    fn adc_gw_ew_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        crate::cpu::arith16::ADC_GwEw(cpu, instr)
    }

    fn adc_ew_gw_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        crate::cpu::arith16::ADC_EwGw(cpu, instr)
    }

    fn adc_ed_gd_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        crate::cpu::arith32::ADC_EdGd_R(cpu, instr);
        Ok(())
    }

    fn adc_gd_ed_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        crate::cpu::arith32::ADC_GdEd_R(cpu, instr);
        Ok(())
    }

    fn mov_al_od_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        crate::cpu::data_xfer8::MOV_ALOd(cpu, instr)
    }

    fn mov_ax_od_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        crate::cpu::data_xfer16::MOV_AXOd(cpu, instr)
    }

    fn mov_od_al_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        crate::cpu::data_xfer8::MOV_OdAL(cpu, instr)
    }

    fn mov_od_ax_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        crate::cpu::data_xfer16::MOV_OdAX(cpu, instr)
    }

    // Wrapper functions for 8-bit MOV instructions (following Bochs data_xfer8.rs)
    fn mov_gb_eb_m_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        crate::cpu::data_xfer8::MOV_GbEbM(cpu, instr)
    }

    fn mov_gb_eb_r_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        crate::cpu::data_xfer8::MOV_GbEbR(cpu, instr)
    }

    fn mov_eb_gb_m_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        crate::cpu::data_xfer8::MOV_EbGbM(cpu, instr)
    }

    fn mov_eb_gb_r_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        crate::cpu::data_xfer8::MOV_EbGbR(cpu, instr)
    }

    fn mov_rb_ib_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        cpu.mov_rb_ib(instr);
        Ok(())
    }

    fn mov_eb_ib_m_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        cpu.mov_eb_ib_m(instr)?;
        Ok(())
    }

    fn mov_gw_ew_r_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        cpu.mov_gw_ew_r(instr);
        Ok(())
    }

    fn mov_gw_ew_m_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        cpu.mov_gw_ew_m(instr)?;
        Ok(())
    }

    fn mov_ew_gw_r_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        cpu.mov_ew_gw_r(instr);
        Ok(())
    }

    fn mov_ew_gw_m_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        cpu.mov_ew_gw_m(instr)?;
        Ok(())
    }

    fn mov_rw_iw_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        cpu.mov_rw_iw(instr);
        Ok(())
    }

    fn mov_ew_iw_m_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        cpu.mov_ew_iw_m(instr)?;
        Ok(())
    }

    fn mov_ew_sw_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        cpu.mov_ew_sw(instr)?;
        Ok(())
    }

    fn mov_sw_ew_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        cpu.mov_sw_ew(instr)?;
        Ok(())
    }

    // Wrapper functions for logical instructions (8-bit)
    fn and_eb_gb_m_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        cpu.and_eb_gb_m(instr)?;
        Ok(())
    }

    fn and_gb_eb_r_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        cpu.and_gb_eb_r(instr);
        Ok(())
    }

    fn and_gb_eb_m_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        cpu.and_gb_eb_m(instr)?;
        Ok(())
    }

    fn and_eb_ib_m_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        cpu.and_eb_ib_m(instr)?;
        Ok(())
    }

    fn or_eb_gb_m_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        cpu.or_eb_gb_m(instr)?;
        Ok(())
    }

    fn or_gb_eb_r_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        cpu.or_gb_eb_r(instr);
        Ok(())
    }

    fn or_gb_eb_m_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        cpu.or_gb_eb_m(instr)?;
        Ok(())
    }

    fn or_eb_ib_m_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        cpu.or_eb_ib_m(instr)?;
        Ok(())
    }

    fn xor_eb_gb_m_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        cpu.xor_eb_gb_m(instr)?;
        Ok(())
    }

    fn xor_gb_eb_r_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        cpu.xor_gb_eb_r(instr);
        Ok(())
    }

    fn xor_gb_eb_m_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        cpu.xor_gb_eb_m(instr)?;
        Ok(())
    }

    fn xor_eb_ib_m_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        cpu.xor_eb_ib_m(instr)?;
        Ok(())
    }

    fn xor_eb_ib_r_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        cpu.xor_eb_ib_r(instr);
        Ok(())
    }

    fn not_eb_m_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        cpu.not_eb_m(instr)?;
        Ok(())
    }

    fn test_eb_gb_m_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        cpu.test_eb_gb_m(instr)?;
        Ok(())
    }

    fn test_eb_ib_m_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        cpu.test_eb_ib_m(instr)?;
        Ok(())
    }

    // Wrapper functions for 32-bit XOR instructions
    fn xor_ed_gd_m_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        cpu.xor_ed_gd_m(instr)?;
        Ok(())
    }

    fn xor_gd_ed_r_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        cpu.xor_gd_ed_r(instr);
        Ok(())
    }

    fn xor_gd_ed_m_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        cpu.xor_gd_ed_m(instr)?;
        Ok(())
    }

    fn zero_idiom_gd_r_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        cpu.zero_idiom_gd_r(instr);
        Ok(())
    }

    // Wrapper functions for 16-bit XOR instructions
    fn xor_ew_gw_m_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        cpu.xor_ew_gw_m(instr)?;
        Ok(())
    }

    fn xor_gw_ew_r_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        cpu.xor_gw_ew_r(instr);
        Ok(())
    }

    fn xor_gw_ew_m_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        cpu.xor_gw_ew_m(instr)?;
        Ok(())
    }

    fn zero_idiom_gw_r_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        cpu.zero_idiom_gw_r(instr);
        Ok(())
    }

    // Wrapper functions for flag manipulation
    fn cli_wrapper<I: BxCpuIdTrait>(cpu: &mut BxCpuC<'_, I>, instr: &Instruction) -> Result<()> {
        cpu.cli(instr)
    }

    fn sti_wrapper<I: BxCpuIdTrait>(cpu: &mut BxCpuC<'_, I>, instr: &Instruction) -> Result<()> {
        cpu.sti(instr)
    }

    fn cld_wrapper<I: BxCpuIdTrait>(cpu: &mut BxCpuC<'_, I>, _instr: &Instruction) -> Result<()> {
        cpu.eflags.remove(super::eflags::EFlags::DF);
        Ok(())
    }

    fn std_wrapper<I: BxCpuIdTrait>(cpu: &mut BxCpuC<'_, I>, _instr: &Instruction) -> Result<()> {
        cpu.eflags.insert(super::eflags::EFlags::DF);
        Ok(())
    }

    // Wrapper functions for I/O instructions
    fn in_al_ib_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        cpu.in_al_ib(instr)
    }

    fn in_ax_ib_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        cpu.in_ax_ib(instr)
    }

    fn in_eax_ib_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        cpu.in_eax_ib(instr)
    }

    fn out_ib_al_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        cpu.out_ib_al(instr)
    }

    fn out_ib_ax_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        cpu.out_ib_ax(instr)
    }

    fn out_ib_eax_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        cpu.out_ib_eax(instr)
    }

    fn in_al_dx_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        cpu.in_al_dx(instr)
    }

    fn in_ax_dx_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        cpu.in_ax_dx(instr)
    }

    fn in_eax_dx_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        cpu.in_eax_dx(instr)
    }

    // Wrapper functions for MOV32S handlers are now at module level (after get_opcode_entry)

    fn out_dx_al_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        cpu.out_dx_al(instr)
    }

    fn out_dx_ax_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        cpu.out_dx_ax(instr)
    }

    fn out_dx_eax_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        cpu.out_dx_eax(instr)
    }

    // Wrapper functions for PUSH/POP segment registers
    fn push_op16_sw_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        let seg = instr.dst() as usize;
        let val = cpu.sregs[seg].selector.value;
        cpu.push_16(val)?;
        Ok(())
    }

    fn pop_op16_sw_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        use crate::cpu::decoder::BxSegregs;
        use crate::cpu::segment_ctrl_pro::parse_selector;
        let seg = instr.dst() as usize;
        let val = cpu.pop_16()?;
        // Don't allow loading CS
        if seg != BxSegregs::Cs as usize {
            parse_selector(val, &mut cpu.sregs[seg].selector);
            unsafe {
                cpu.sregs[seg].cache.u.segment.base = (val as u64) << 4;
            }
        }
        Ok(())
    }

    // Wrapper function for PUSH immediate 32-bit
    fn push_id_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        cpu.push_id(instr)?;
        Ok(())
    }

    // Wrapper function for FAR JMP (needs TRACE_END flag)
    fn jmpf_ap_wrapper<I: BxCpuIdTrait>(
        cpu: &mut BxCpuC<'_, I>,
        instr: &Instruction,
    ) -> Result<()> {
        // Check if this is 16-bit or 32-bit far jump by examining instruction length
        // Far jump encoding:
        //   16-bit: EA <2-byte offset> <2-byte selector> = 5 bytes
        //   32-bit: EA <4-byte offset> <2-byte selector> = 7 bytes
        // With 0x66 prefix: add 1 byte
        let segment = instr.iw2();

        // Try reading as 32-bit first
        let offset32 = instr.id();
        let offset16 = instr.iw() as u32;

        // If instruction length suggests 32-bit (>= 6 bytes including opcode),
        // or if the 32-bit value is significantly different from 16-bit, use 32-bit
        if instr.ilen() >= 6 && offset32 != offset16 {
            // 32-bit far jump
            tracing::debug!("JmpfAp(w): FAR JMP 32-BIT to {:04x}:{:08x}", segment, offset32);
            cpu.jmp_far32(instr, segment, offset32)?;
        } else {
            // 16-bit far jump
            tracing::debug!("JmpfAp(w): FAR JMP 16-BIT to {:04x}:{:04x}", segment, offset16);
            cpu.jmp_far16(instr, segment, offset16 as u16)?;
        }

        Ok(())
    }

    // Match on opcode and return appropriate entry
    // This is a placeholder - will be extended with all opcodes
    match opcode {
        // Data transfer instructions - 32-bit
        Opcode::MovOp32GdEd => Some(BxOpcodeEntry {
            execute1: mov_gd_ed_m_wrapper,       // Memory form: MOV r32, [mem]
            execute2: Some(mov_gd_ed_r_wrapper), // Register form: MOV r32, r32
            opflags: OpFlags::empty(),
        }),
        Opcode::MovOp32EdGd => Some(BxOpcodeEntry {
            execute1: mov_ed_gd_m_wrapper,       // Memory form: MOV [mem], r32
            execute2: Some(mov_ed_gd_r_wrapper), // Register form: MOV r32, r32
            opflags: OpFlags::empty(),
        }),
        Opcode::MovEdId => Some(BxOpcodeEntry {
            execute1: mov_ed_id_m_wrapper,       // Memory form: MOV [mem], imm32
            execute2: Some(mov_ed_id_r_wrapper), // Register form: MOV r32, imm32
            opflags: OpFlags::empty(),
        }),

        // Arithmetic instructions - 8-bit
        Opcode::AddEbGb => Some(BxOpcodeEntry {
            execute1: add_eb_gb_wrapper,       // Memory form
            execute2: Some(add_eb_gb_wrapper), // Register form — same unified dispatcher
            opflags: OpFlags::LOCKABLE,
        }),
        Opcode::AddGbEb => Some(BxOpcodeEntry {
            execute1: add_gb_eb_wrapper,       // Memory form
            execute2: Some(add_gb_eb_wrapper), // Register form (same for now)
            opflags: OpFlags::empty(),
        }),

        // Arithmetic instructions - 32-bit
        Opcode::AddGdEd => Some(BxOpcodeEntry {
            execute1: add_gd_ed_m_wrapper,       // Memory form: ADD r32, [mem]
            execute2: Some(add_gd_ed_r_wrapper), // Register form: ADD r32, r32
            opflags: OpFlags::empty(),
        }),
        Opcode::AddEdGd => Some(BxOpcodeEntry {
            execute1: add_ed_gd_m_wrapper,       // Memory form: ADD [mem], r32
            execute2: Some(add_ed_gd_r_wrapper), // Register form: ADD r32, r32
            opflags: OpFlags::LOCKABLE,
        }),
        Opcode::AddEaxid => Some(BxOpcodeEntry {
            execute1: add_eax_id_wrapper,
            execute2: None,
            opflags: OpFlags::empty(),
        }),
        Opcode::AddAlib => Some(BxOpcodeEntry {
            execute1: add_eb_ib_wrapper,
            execute2: Some(add_eb_ib_wrapper),
            opflags: OpFlags::empty(),
        }),
        Opcode::AddEwsIb => Some(BxOpcodeEntry {
            execute1: add_ew_ib_m_wrapper,       // Memory form: ADD [mem], imm8
            execute2: Some(add_ew_ib_r_wrapper), // Register form: ADD r16, imm8
            opflags: OpFlags::empty(),
        }),
        // AddEbIb: falls through to execute_instruction (unified dispatch)
        // Both forms previously used register-only handler — bug fixed by removal

        // Arithmetic (SUB) instructions - 32-bit
        Opcode::SubGdEd => Some(BxOpcodeEntry {
            execute1: sub_gd_ed_m_wrapper,       // Memory form: SUB r32, [mem]
            execute2: Some(sub_gd_ed_r_wrapper), // Register form: SUB r32, r32
            opflags: OpFlags::empty(),
        }),
        Opcode::SubEdGd => Some(BxOpcodeEntry {
            execute1: sub_ed_gd_m_wrapper,       // Memory form: SUB [mem], r32
            execute2: Some(sub_ed_gd_r_wrapper), // Register form: SUB r32, r32
            opflags: OpFlags::LOCKABLE,
        }),
        Opcode::SubEaxid => Some(BxOpcodeEntry {
            execute1: sub_eax_id_wrapper,
            execute2: None,
            opflags: OpFlags::empty(),
        }),

        // Arithmetic (ADC) instructions
        Opcode::AdcEbGb => Some(BxOpcodeEntry {
            execute1: adc_eb_gb_wrapper,
            execute2: None,
            opflags: OpFlags::empty(),
        }),
        Opcode::AdcGwEw => Some(BxOpcodeEntry {
            execute1: adc_gw_ew_wrapper,
            execute2: Some(adc_gw_ew_wrapper),
            opflags: OpFlags::empty(),
        }),
        Opcode::AdcEwGw => Some(BxOpcodeEntry {
            execute1: adc_ew_gw_wrapper,
            execute2: Some(adc_ew_gw_wrapper),
            opflags: OpFlags::empty(),
        }),
        // AdcEdGd/AdcGdEd: falls through to execute_instruction (unified dispatch)
        // Both forms previously used _R (register-only) handler — bug fixed by removal

        // Data transfer (MOV) instructions - direct memory
        Opcode::MovAlod => Some(BxOpcodeEntry {
            execute1: mov_al_od_wrapper,
            execute2: None,
            opflags: OpFlags::empty(),
        }),
        Opcode::MovAxod => Some(BxOpcodeEntry {
            execute1: mov_ax_od_wrapper,
            execute2: None,
            opflags: OpFlags::empty(),
        }),
        Opcode::MovOdAl => Some(BxOpcodeEntry {
            execute1: mov_od_al_wrapper,
            execute2: None,
            opflags: OpFlags::empty(),
        }),
        Opcode::MovOdAx => Some(BxOpcodeEntry {
            execute1: mov_od_ax_wrapper,
            execute2: None,
            opflags: OpFlags::empty(),
        }),

        // Data transfer (MOV) instructions - 8-bit
        // Opcode 0x8A: MOV r8, r/m8 - Load register from memory/register
        Opcode::MovGbEb => Some(BxOpcodeEntry {
            execute1: mov_gb_eb_m_wrapper,       // Memory form: MOV r8, [mem]
            execute2: Some(mov_gb_eb_r_wrapper), // Register form: MOV r8, r8
            opflags: OpFlags::empty(),
        }),
        // Opcode 0x88: MOV r/m8, r8 - Store register to memory/register
        Opcode::MovEbGb => Some(BxOpcodeEntry {
            execute1: mov_eb_gb_m_wrapper,       // Memory form: MOV [mem], r8
            execute2: Some(mov_eb_gb_r_wrapper), // Register form: MOV r8, r8
            opflags: OpFlags::empty(),
        }),
        Opcode::MovEbIb => Some(BxOpcodeEntry {
            execute1: mov_eb_ib_m_wrapper,     // Memory form: MOV [mem], imm8
            execute2: Some(mov_rb_ib_wrapper), // Register form: MOV r8, imm8
            opflags: OpFlags::empty(),
        }),

        // Data transfer (MOV) instructions - 16-bit
        Opcode::MovGwEw => Some(BxOpcodeEntry {
            execute1: mov_gw_ew_m_wrapper,       // Memory form: MOV r16, [mem]
            execute2: Some(mov_gw_ew_r_wrapper), // Register form: MOV r16, r16
            opflags: OpFlags::empty(),
        }),
        Opcode::MovEwGw => Some(BxOpcodeEntry {
            execute1: mov_ew_gw_m_wrapper,       // Memory form: MOV [mem], r16
            execute2: Some(mov_ew_gw_r_wrapper), // Register form: MOV r16, r16
            opflags: OpFlags::empty(),
        }),
        Opcode::MovEwIw => Some(BxOpcodeEntry {
            execute1: mov_ew_iw_m_wrapper,     // Memory form: MOV [mem], imm16
            execute2: Some(mov_rw_iw_wrapper), // Register form: MOV r16, imm16
            opflags: OpFlags::empty(),
        }),

        // Segment register MOV
        Opcode::MovEwSw => Some(BxOpcodeEntry {
            execute1: mov_ew_sw_wrapper,
            execute2: None,
            opflags: OpFlags::empty(),
        }),
        Opcode::MovSwEw => Some(BxOpcodeEntry {
            execute1: mov_sw_ew_wrapper,
            execute2: None,
            opflags: OpFlags::empty(),
        }),

        // Logical instructions - 8-bit (AND)
        Opcode::AndEbGb => Some(BxOpcodeEntry {
            execute1: and_eb_gb_m_wrapper, // Memory form
            execute2: None,                // Register form handled separately
            opflags: OpFlags::empty(),
        }),
        Opcode::AndGbEb => Some(BxOpcodeEntry {
            execute1: and_gb_eb_m_wrapper,       // Memory form
            execute2: Some(and_gb_eb_r_wrapper), // Register form
            opflags: OpFlags::empty(),
        }),
        Opcode::AndEbIb => Some(BxOpcodeEntry {
            execute1: and_eb_ib_m_wrapper, // Memory form
            execute2: None,                // Register form handled separately
            opflags: OpFlags::empty(),
        }),

        // Logical instructions - 8-bit (OR)
        Opcode::OrEbGb => Some(BxOpcodeEntry {
            execute1: or_eb_gb_m_wrapper, // Memory form
            execute2: None,               // Register form handled separately
            opflags: OpFlags::empty(),
        }),
        Opcode::OrGbEb => Some(BxOpcodeEntry {
            execute1: or_gb_eb_m_wrapper,       // Memory form
            execute2: Some(or_gb_eb_r_wrapper), // Register form
            opflags: OpFlags::empty(),
        }),
        Opcode::OrEbIb => Some(BxOpcodeEntry {
            execute1: or_eb_ib_m_wrapper, // Memory form
            execute2: None,               // Register form handled separately
            opflags: OpFlags::empty(),
        }),

        // Logical instructions - 8-bit (XOR)
        Opcode::XorEbGb => Some(BxOpcodeEntry {
            execute1: xor_eb_gb_m_wrapper, // Memory form
            execute2: None,                // Register form handled separately
            opflags: OpFlags::empty(),
        }),
        Opcode::XorGbEb => Some(BxOpcodeEntry {
            execute1: xor_gb_eb_m_wrapper,       // Memory form
            execute2: Some(xor_gb_eb_r_wrapper), // Register form
            opflags: OpFlags::empty(),
        }),
        Opcode::XorEbIb => Some(BxOpcodeEntry {
            execute1: xor_eb_ib_m_wrapper,       // Memory form
            execute2: Some(xor_eb_ib_r_wrapper), // Register form
            opflags: OpFlags::empty(),
        }),
        Opcode::XorAlib => Some(BxOpcodeEntry {
            execute1: xor_eb_ib_r_wrapper, // Register form (AL, imm8)
            execute2: None,
            opflags: OpFlags::empty(),
        }),

        // Logical instructions - 32-bit (XOR)
        Opcode::XorEdGd => Some(BxOpcodeEntry {
            execute1: xor_ed_gd_m_wrapper, // Memory form
            execute2: None,                // Register form handled separately
            opflags: OpFlags::empty(),
        }),
        Opcode::XorGdEd => Some(BxOpcodeEntry {
            execute1: xor_gd_ed_m_wrapper,       // Memory form
            execute2: Some(xor_gd_ed_r_wrapper), // Register form
            opflags: OpFlags::empty(),
        }),
        Opcode::XorEdGdZeroIdiom | Opcode::XorGdEdZeroIdiom => Some(BxOpcodeEntry {
            execute1: zero_idiom_gd_r_wrapper,
            execute2: None,
            opflags: OpFlags::empty(),
        }),

        // Logical instructions - 16-bit (XOR)
        Opcode::XorEwGw => Some(BxOpcodeEntry {
            execute1: xor_ew_gw_m_wrapper, // Memory form
            execute2: None,                // Register form handled separately
            opflags: OpFlags::empty(),
        }),
        Opcode::XorGwEw => Some(BxOpcodeEntry {
            execute1: xor_gw_ew_m_wrapper,       // Memory form
            execute2: Some(xor_gw_ew_r_wrapper), // Register form
            opflags: OpFlags::empty(),
        }),
        Opcode::XorEwGwZeroIdiom | Opcode::XorGwEwZeroIdiom => Some(BxOpcodeEntry {
            execute1: zero_idiom_gw_r_wrapper,
            execute2: None,
            opflags: OpFlags::empty(),
        }),

        // Logical instructions - 8-bit (NOT, TEST)
        Opcode::NotEb => Some(BxOpcodeEntry {
            execute1: not_eb_m_wrapper, // Memory form
            execute2: None,             // Register form handled separately
            opflags: OpFlags::empty(),
        }),
        Opcode::TestEbGb => Some(BxOpcodeEntry {
            execute1: test_eb_gb_m_wrapper, // Memory form
            execute2: None,                 // Register form handled separately
            opflags: OpFlags::empty(),
        }),
        Opcode::TestEbIb => Some(BxOpcodeEntry {
            execute1: test_eb_ib_m_wrapper, // Memory form
            execute2: None,                 // Register form handled separately
            opflags: OpFlags::empty(),
        }),

        // CMP (Compare) instructions
        Opcode::CmpGbEb => Some(BxOpcodeEntry {
            execute1: cmp_gb_eb_m_wrapper,       // Memory form: CMP r8, [mem]
            execute2: Some(cmp_gb_eb_r_wrapper), // Register form: CMP r8, r8
            opflags: OpFlags::empty(),
        }),
        Opcode::CmpEbGb => Some(BxOpcodeEntry {
            execute1: cmp_eb_gb_m_wrapper,       // Memory form: CMP [mem], r8
            execute2: Some(cmp_eb_gb_r_wrapper), // Register form: CMP r/m8, r8
            opflags: OpFlags::empty(),
        }),
        Opcode::CmpGwEw => Some(BxOpcodeEntry {
            execute1: cmp_gw_ew_m_wrapper,       // Memory form: CMP r16, [mem]
            execute2: Some(cmp_gw_ew_r_wrapper), // Register form: CMP r16, r16
            opflags: OpFlags::empty(),
        }),
        Opcode::CmpGdEd => Some(BxOpcodeEntry {
            execute1: cmp_gd_ed_m_wrapper,       // Memory form: CMP r32, [mem]
            execute2: Some(cmp_gd_ed_r_wrapper), // Register form: CMP r32, r32
            opflags: OpFlags::empty(),
        }),
        Opcode::CmpAlib => Some(BxOpcodeEntry {
            execute1: cmp_al_ib_wrapper,
            execute2: None, // Register form only (AL is implicit)
            opflags: OpFlags::empty(),
        }),
        Opcode::CmpAxiw => Some(BxOpcodeEntry {
            execute1: cmp_ax_iw_wrapper,
            execute2: None, // Register form only (AX is implicit)
            opflags: OpFlags::empty(),
        }),
        Opcode::CmpEaxid => Some(BxOpcodeEntry {
            execute1: cmp_eax_id_wrapper,
            execute2: None, // Register form only (EAX is implicit)
            opflags: OpFlags::empty(),
        }),
        Opcode::CmpEwIw => Some(BxOpcodeEntry {
            execute1: cmp_ew_iw_m_wrapper,       // Memory form: CMP [mem], imm16
            execute2: Some(cmp_ew_iw_r_wrapper), // Register form: CMP r16, imm16
            opflags: OpFlags::empty(),
        }),
        Opcode::CmpEdId => Some(BxOpcodeEntry {
            execute1: cmp_ed_id_m_wrapper,       // Memory form: CMP [mem], imm32
            execute2: Some(cmp_ed_id_r_wrapper), // Register form: CMP r32, imm32
            opflags: OpFlags::empty(),
        }),
        // CmpEbIb: falls through to execute_instruction (unified dispatch)
        // Wrapper was register-only (get_gpr8 instead of read_virtual_byte) — bug fixed by removal

        // Error handlers (matching C++ BX_IA_ERROR and BX_INSERTED_OPCODE)
        Opcode::IaError => Some(BxOpcodeEntry {
            execute1: bx_error_wrapper,
            execute2: Some(bx_error_wrapper),
            opflags: OpFlags::TRACE_END,
        }),
        Opcode::InsertedOpcode => Some(BxOpcodeEntry {
            execute1: bx_end_trace_wrapper,
            execute2: Some(bx_end_trace_wrapper),
            opflags: OpFlags::empty(),
        }),

        // Flag manipulation instructions
        Opcode::Cli => Some(BxOpcodeEntry {
            execute1: cli_wrapper,
            execute2: None,
            opflags: OpFlags::empty(),
        }),
        Opcode::Sti => Some(BxOpcodeEntry {
            execute1: sti_wrapper,
            execute2: None,
            opflags: OpFlags::empty(),
        }),
        Opcode::Cld => Some(BxOpcodeEntry {
            execute1: cld_wrapper,
            execute2: None,
            opflags: OpFlags::empty(),
        }),
        Opcode::Std => Some(BxOpcodeEntry {
            execute1: std_wrapper,
            execute2: None,
            opflags: OpFlags::empty(),
        }),

        // I/O port instructions - immediate port
        Opcode::InAlib => Some(BxOpcodeEntry {
            execute1: in_al_ib_wrapper,
            execute2: None,
            opflags: OpFlags::empty(),
        }),
        Opcode::InAxib => Some(BxOpcodeEntry {
            execute1: in_ax_ib_wrapper,
            execute2: None,
            opflags: OpFlags::empty(),
        }),
        Opcode::InEaxib => Some(BxOpcodeEntry {
            execute1: in_eax_ib_wrapper,
            execute2: None,
            opflags: OpFlags::empty(),
        }),
        Opcode::OutIbAl => Some(BxOpcodeEntry {
            execute1: out_ib_al_wrapper,
            execute2: None,
            opflags: OpFlags::empty(),
        }),
        Opcode::OutIbAx => Some(BxOpcodeEntry {
            execute1: out_ib_ax_wrapper,
            execute2: None,
            opflags: OpFlags::empty(),
        }),
        Opcode::OutIbEax => Some(BxOpcodeEntry {
            execute1: out_ib_eax_wrapper,
            execute2: None,
            opflags: OpFlags::empty(),
        }),

        // I/O port instructions - DX port
        Opcode::InAlDx => Some(BxOpcodeEntry {
            execute1: in_al_dx_wrapper,
            execute2: None,
            opflags: OpFlags::empty(),
        }),
        Opcode::InAxDx => Some(BxOpcodeEntry {
            execute1: in_ax_dx_wrapper,
            execute2: None,
            opflags: OpFlags::empty(),
        }),
        Opcode::InEaxDx => Some(BxOpcodeEntry {
            execute1: in_eax_dx_wrapper,
            execute2: None,
            opflags: OpFlags::empty(),
        }),
        Opcode::OutDxAl => Some(BxOpcodeEntry {
            execute1: out_dx_al_wrapper,
            execute2: None,
            opflags: OpFlags::empty(),
        }),
        Opcode::OutDxAx => Some(BxOpcodeEntry {
            execute1: out_dx_ax_wrapper,
            execute2: None,
            opflags: OpFlags::empty(),
        }),
        Opcode::OutDxEax => Some(BxOpcodeEntry {
            execute1: out_dx_eax_wrapper,
            execute2: None,
            opflags: OpFlags::empty(),
        }),

        // PUSH/POP segment registers
        Opcode::PushOp16Sw => Some(BxOpcodeEntry {
            execute1: push_op16_sw_wrapper,
            execute2: None,
            opflags: OpFlags::empty(),
        }),
        Opcode::PopOp16Sw => Some(BxOpcodeEntry {
            execute1: pop_op16_sw_wrapper,
            execute2: None,
            opflags: OpFlags::empty(),
        }),

        // PUSH immediate 32-bit
        Opcode::PushId => Some(BxOpcodeEntry {
            execute1: push_id_wrapper,
            execute2: None,
            opflags: OpFlags::empty(),
        }),

        // FAR JMP (needs TRACE_END flag)
        Opcode::JmpfAp => Some(BxOpcodeEntry {
            execute1: jmpf_ap_wrapper,
            execute2: None,
            opflags: OpFlags::TRACE_END,
        }),

        // NOP
        Opcode::Nop => Some(BxOpcodeEntry {
            execute1: |_cpu: &mut BxCpuC<'_, I>, _instr: &Instruction| -> Result<()> { Ok(()) },
            execute2: None,
            opflags: OpFlags::empty(),
        }),

        // Default: opcode not yet in table
        // Note: Many opcodes are handled by methods on BxCpuC (like mov_gb_eb_r, and_gb_eb_r, etc.)
        // These need to be wrapped differently. For now, they will fall through to execute_instruction
        _ => None,
    }
}

// Error handler wrappers (moved outside get_opcode_entry to be accessible)
pub(super) fn bx_no_fpu_wrapper<I: BxCpuIdTrait>(
    cpu: &mut BxCpuC<'_, I>,
    instr: &Instruction,
) -> Result<()> {
    cpu.bx_no_fpu(instr)
}

pub(super) fn bx_no_mmx_wrapper<I: BxCpuIdTrait>(
    cpu: &mut BxCpuC<'_, I>,
    instr: &Instruction,
) -> Result<()> {
    cpu.bx_no_mmx(instr)
}

#[cfg(feature = "bx_support_sse")]
pub(super) fn bx_no_sse_wrapper<I: BxCpuIdTrait>(
    cpu: &mut BxCpuC<'_, I>,
    instr: &Instruction,
) -> Result<()> {
    cpu.bx_no_sse(instr)
}

#[cfg(feature = "bx_support_avx")]
pub(super) fn bx_no_avx_wrapper<I: BxCpuIdTrait>(
    cpu: &mut BxCpuC<'_, I>,
    instr: &Instruction,
) -> Result<()> {
    cpu.bx_no_avx(instr)
}

#[cfg(feature = "bx_support_evex")]
pub(super) fn bx_no_opmask_wrapper<I: BxCpuIdTrait>(
    cpu: &mut BxCpuC<'_, I>,
    instr: &Instruction,
) -> Result<()> {
    cpu.bx_no_opmask(instr)
}

#[cfg(feature = "bx_support_evex")]
pub(super) fn bx_no_evex_wrapper<I: BxCpuIdTrait>(
    cpu: &mut BxCpuC<'_, I>,
    instr: &Instruction,
) -> Result<()> {
    cpu.bx_no_evex(instr)
}

#[cfg(feature = "bx_support_amx")]
pub(super) fn bx_no_amx_wrapper<I: BxCpuIdTrait>(
    cpu: &mut BxCpuC<'_, I>,
    instr: &Instruction,
) -> Result<()> {
    cpu.bx_no_amx(instr)
}

// MOV32S wrappers (moved outside get_opcode_entry to be accessible)
pub(super) fn mov32s_gd_ed_m_wrapper<I: BxCpuIdTrait>(
    cpu: &mut BxCpuC<'_, I>,
    instr: &Instruction,
) -> Result<()> {
    cpu.mov32s_gd_ed_m(instr)?;
    Ok(())
}

pub(super) fn mov32s_ed_gd_m_wrapper<I: BxCpuIdTrait>(
    cpu: &mut BxCpuC<'_, I>,
    instr: &Instruction,
) -> Result<()> {
    cpu.mov32s_ed_gd_m(instr)?;
    Ok(())
}
